name: 'Configure AWS Credentials'
description: 'Reusable action to configure AWS credentials using OIDC'

inputs:
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'eu-west-1'
  role-arn:
    description: 'AWS IAM Role ARN'
    required: true
  role-session-name:
    description: 'Role session name'
    required: false
    default: 'GitHubActions'

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.role-arn }}
      aws-region: ${{ inputs.aws-region }}
      role-session-name: ${{ inputs.role-session-name }}

  - name: Verify AWS Identity
    shell: bash
    run: |
      echo "AWS Account: $(aws sts get-caller-identity --query Account --output text)"
      echo "AWS Region: $(aws configure get region)"
