#!/bin/bash
# Quick SNS Setup Guide

echo "=== SNS Notification System Setup ==="
echo ""
echo "1. Update terraform.tfvars with your notification emails:"
echo "   notification_emails = [\"your-email@amalitech.com\", \"admin@amalitech.com\"]"
echo ""
echo "2. Deploy infrastructure:"
echo "   cd terraform && terraform apply"
echo ""
echo "3. Deploy Lambda function:"
echo "   cd ../lambda/notification-handler"
echo "   zip -r function.zip index.js node_modules/ package*.json"
echo "   aws lambda update-function-code --function-name task-manager-sandbox-notification-handler --zip-file fileb://function.zip"
echo ""
echo "4. Confirm email subscription:"
echo "   - Check your email inbox"
echo "   - Click the AWS SNS confirmation link"
echo ""
echo "5. Test notifications:"
echo "   - Assign a task to a user"
echo "   - All subscribers will receive notification"
echo ""
echo "=== OR use the automated script ==="
echo "   ./scripts/deploy-sns.sh"
echo ""
